server:
  port: 9192

spring:
  datasource:
    url: jdbc:mysql://monorail.proxy.rlwy.net:57609/railway
    username: root
    password: mwAuuFmjfSjMpPILgGphncZBdoFdUxbD
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB

app:
  server:
    domain: https://bidbaybe.site

  auth:
    secret-key: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D
    expire-length: 3600000

